//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoAppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int id { get; set; }
        public string task { get; set; }
        public System.DateTime dateTime { get; set; }
        public byte hasDoneTask { get; set; }
    }
}
