//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbteilungsbaumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Parent_Id { get; set; }
    }

    //public partial class Department
    //{
    //    over
    //}
}
